[tool.poetry]
name = "gerion-cli"
version = "0.1.0"
description = "A powerful command-line interface for performing security scans on your codebase"
authors = ["gerion-appsec <info@gerion-appsec.com>"]
readme = "README.md"

[tool.poetry.scripts]
gerion-cli = "gerion_cli.main:app"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.15.2"
gitpython = "^3.1.44"
httpx = "^0.27.0"
rich = "^13.7.0"
pydantic = "^2.6.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
