[tool.poetry]
name = "gerion-cli"
version = "1.0.0"
description = "A powerful command-line interface for performing security scans on your codebase"
authors = ["gerion-appsec <info@gerion-appsec.com>"]
readme = "README.md"

[tool.poetry.scripts]
gerion = "gerion_cli.main:app"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.24.0"
gitpython = "^3.1.44"
httpx = "^0.28.0"
rich = "^14.0.0"
pydantic = "^2.6.0"
fpdf2 = "^2.8.5"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
